### ISSUE TITLE
identifier-BRC.ttl: define https://www.brreg.no

### ISSUE THREAD

**Issue by VladimirAlexiev** [euBusinessGraph/eubg-data#10]
I see great additions in https://github.com/euBusinessGraph/eubg-data/blob/master/data/identifier/identifier-BRC.ttl and I think @bgrova made some changes so I see you now have access.
- @bgrova please provide some info about `<https://www.brreg.no>` (see `<https://www.registryagency.bg>` in identifier-BG.ttl)
- @bgrova go through the file and edit some of the comments (eg "conneg is expected to be functional on ..." and remove those at end of file)
- @bmzernichow uses a slightly different URL in company data (`dct:creator`):    `<https://www.brreg.no>` (no trailing slash). Please use the same URL: remove the trailing slash from identifier-BRC.ttl because it's just 1 file

**Comment by bgrova** [comment]
I have commited some changes to identifier-BRC.ttl. Still awaiting some info about content negotiation, and will commit further changes when i get this info.

**Comment by bmzernichow** [comment]
Completed the following action items:
- Provided info about <https://www.brreg.no> in commit 57d6404ae8bba68b83e8ae24ea28c78e324f0050
- Removed trailing slash from <https://www.brreg.no> in commit 57d6404ae8bba68b83e8ae24ea28c78e324f0050
