### ISSUE TITLE
UK LAU

### ISSUE THREAD

**Issue by VladimirAlexiev** [euBusinessGraph/eubg-data#11]
OCORP data includes all address admin units, eg
```Turtle
        locn:adminUnitL1   nuts:UK ;
        locn:adminUnitL2   nuts:UKI ;
        ebg:adminUnitL3    nuts:UKI2 ;
        ebg:adminUnitL4    nuts:UKI22 ;
        ebg:adminUnitL5    lau:E09000024 ;
        ebg:adminUnitL6    lau:E05000455 ;
```
Unfortunately we don't have UK LAU in `eubg-data\data\LAU\rdf`.
We have some tabular data in https://github.com/euBusinessGraph/eubg-data/tree/master/data/LAU, could you try to make RDF out of it?
- `data\LAU2\uk.csv`
- `LAU216_LAU116_NUTS315_NUTS215_NUTS115_UK_LU.csv`

**Comment by bmzernichow** [comment]
Generated UK LAU for both levels ebg:adminUnitL5 and ebg:adminUnitL6 in commit 57d6404ae8bba68b83e8ae24ea28c78e324f0050

**Comment by VladimirAlexiev** [comment]
- @uk is not a language, kill those labels since they duplicate en labels
- each level needs to link to the level above. See the other lau ttl for examples

@bmzernichow

**Comment by VladimirAlexiev** [comment]
- the parent link is added
- the data about level 4 LAUs is spread across `uk-lau4` and `uk-lau5`, would be best to consolidate it in `uk-lau4`
