### ISSUE TITLE
harmonize company types

### ISSUE THREAD

**Issue by VladimirAlexiev** [euBusinessGraph/eubg-data#9]
cc @bmzernichow @bgrova 
https://github.com/euBusinessGraph/eubg-data/tree/master/data/lookups
- Currently we have these files:
EBG-company-type.xlsx: saved from gsheet
EBG-company-type.csv: saved from xls
EBG-company-type.tarql: converts to ttl but only "BG" codes
EBG-company-type.ttl: BG, converted by tarql
EBG-company-type-brc.ttl: made by hand?
EBG-company-type-ocorp-uk.ttl: made by hand?
EBG-company-type-sdati-it.ttl: made by hand?
- my idea was to edit the xls (or gsheet) and then generate for all jurisdictions from it. I know that @bgrova made a xls on dropbox, it was a matter of only unifying those xls. Do you agree to work in a common excel?
- also, we have differing concept schemes:
```ttl
<type/BG/ET>  rdf:type  skos:Concept ;
        skos:inScheme   <type> ;
# but then
<type/NO> a skos:ConceptScheme; 
        rdfs:label "NO company types"@en, "NO organisasjonsform"@no .

<type/NO/NUF> a skos:Concept ;
        skos:inScheme   <type/NO> ;
```
- I think the model specifies a single scheme, not per-jurisdiction. If you agree, then I must make a `<type>` scheme.
- BG has consecutive `ebg:order` whereas NO has all set to `1`. This makes the order useless. If there is some meaningful order to those codes (eg he most  popular first), use `ebg:order` else omit it. But don't use a constant `1`

**Comment by bgrova** [comment]
There is no inherent order in the NO organization types, but the most common ones are ENK and AS.

**Comment by VladimirAlexiev** [comment]
Then put them as 1,2 and the rest with no `ebg:order`
